// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPANQb9leQ9N3teDd5KGR31kxFHXD-RCs',
    appId: '1:244040791955:web:aa42b8425c14324e845a66',
    messagingSenderId: '244040791955',
    projectId: 'regesteration-system',
    authDomain: 'regesteration-system.firebaseapp.com',
    storageBucket: 'regesteration-system.appspot.com',
    measurementId: 'G-YMBMJQ43KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeKpHbPfHCUYa7Cplk5giCweEy2N5G1Ws',
    appId: '1:244040791955:android:ac14ca95871079e7845a66',
    messagingSenderId: '244040791955',
    projectId: 'regesteration-system',
    storageBucket: 'regesteration-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEouIf_tMg-rWk-qQ0L2LgrufpzECmS3c',
    appId: '1:244040791955:ios:3d30f799ee2dc48c845a66',
    messagingSenderId: '244040791955',
    projectId: 'regesteration-system',
    storageBucket: 'regesteration-system.appspot.com',
    androidClientId: '244040791955-lddu00tv461jjvcehku06o9m934bkjk1.apps.googleusercontent.com',
    iosClientId: '244040791955-e06najegbfb7fbgbd74s6tbb57vsl3s8.apps.googleusercontent.com',
    iosBundleId: 'com.example.gasserGraduation',
  );
}
